"""
Каталог Cofem — оновлено з реальних прайсів (11.05.2026)
Джерела:
  • FireCompare_Catalog_Forms.xlsx (панелі, A50, оповіщувачі)
  • Cofem_module.xlsx (I/O модулі, додаткові детектори, MCP, база)
Курс євро/гривня: 52.5

Ціни без ПДВ. Для панелей з FireCompare поділено на 1.2 (там були з ПДВ).
"""
from datetime import date

from schemas.catalog import (
    BMSIntegration, Certifications, CertificationStatus, CloudMonitoring,
    DataStatus, Detector, DetectorType, FalseAlarmLevel, FeatureSupport,
    Features, IOModule, IOModuleType, JurisdictionCert, ManualCallPoint,
    Manufacturer, MobileApp, Panel, PanelType, PricingStatus, Redundancy,
    Sounder, SystemType, Tier, UADistributor,
)


# Спільний список панелей Cofem, які приймають всі компоненти
_ALL_COFEM_PANELS = [
    "cofem_rubi", "cofem_quartz_1", "cofem_quartz_2",
    "cofem_compact_lyon_1", "cofem_compact_lyon_2",
    "cofem_zafir_1", "cofem_zafir_2",
    "cofem_onyx_1", "cofem_onyx_2",
    "cofem_lyon_1", "cofem_lyon_2", "cofem_lyon_3", "cofem_lyon_4",
    "cofem_lyon_5", "cofem_lyon_6", "cofem_lyon_7", "cofem_lyon_8",
]

# Лише панелі, які підтримують I/O модулі (без Rubi/Quartz — компакти без модулів)
_PANELS_WITH_IO = [p for p in _ALL_COFEM_PANELS if p not in ("cofem_rubi", "cofem_quartz_1", "cofem_quartz_2")]


COFEM = Manufacturer(
    manufacturer_id="cofem",
    name_ua="Cofem",
    name_en="Cofem",
    country_iso2="ES",
    founded_year=1973,
    tier=Tier.PREMIUM,
    system_type=SystemType.ALGORITHMIC,
    warranty_months=24,
    extended_warranty_available=True,
    ua_distributor=UADistributor(
        company_name="(уточнити — поточний UA-дистриб'ютор)",
        service_cities=["Київ", "Львів", "Дніпро", "Одеса"],
        response_time_hours=48,
    ),
    data_status=DataStatus.COMPLETE,
    last_updated=date(2026, 5, 11),
    notes_internal="Ціни оновлено з прайс-листа дистриб'ютора 11.05.2026. Курс 52.5 грн/євро.",
    notes_strengths=[
        "Алгоритмічна детекція з drift compensation",
        "1-адресні I/O модулі (MSTAY8 на 8 входів, MDA2YLT на 2 реле) — економія адрес",
        "Native cloud (Cofem Remote / Cofem 360)",
        "EN 54 + CE — підходить для дуальної UA+UK юрисдикції",
        "Voice alarm інтеграція через сертифікованих партнерів",
        "Інтегрований сповіщувач A50SHILD (дим+тепло+сирена+строб)",
    ],
    notes_weaknesses=[
        "Вищий CAPEX за UA-бренди",
        "ДСТУ EN 54 в процесі сертифікації",
        "BMS-інтеграція через шлюз, не нативна",
    ],
    certifications=Certifications(
        EU_EN54=JurisdictionCert(
            status=CertificationStatus.FULL,
            certified_parts=["-2", "-4", "-7", "-17", "-18", "-23"],
            certification_body="AENOR",
        ),
        UA_DSTU_EN54=JurisdictionCert(
            status=CertificationStatus.IN_PROCESS,
            notes="Процес активний; покривається професійною відповідальністю проєктувальника",
        ),
        UK_BS_LPCB=JurisdictionCert(
            status=CertificationStatus.FULL,
            notes="EN 54 + CE приймається в UK через міжнародну гармонізацію",
        ),
        US_UL_FM=JurisdictionCert(status=CertificationStatus.NONE),
        iso_9001="ISO 9001:2015",
    ),
    features=Features(
        false_alarm_level=FalseAlarmLevel.PREMIUM,
        false_alarm_technologies=["drift_compensation", "adaptive_thresholds", "algorithmic_signal_analysis"],
        cloud_monitoring=CloudMonitoring(available=True, platform_name="Cofem Remote / Cofem 360"),
        mobile_app=MobileApp(available=True, platforms=["iOS", "Android"]),
        bms_integration=BMSIntegration(
            bacnet=FeatureSupport.GATEWAY,
            modbus_rtu=FeatureSupport.GATEWAY,
            modbus_tcp=FeatureSupport.GATEWAY,
        ),
        voice_alarm=FeatureSupport.PARTNER,
        wireless_extension=False,
        redundancy=Redundancy(),
    ),
    panels=[
        Panel(panel_id="cofem_rubi", model_name="Rubí (1 шлейф)",
              panel_type=PanelType.COMPACT, max_loops=1, devices_per_loop=64, max_total_devices=64,
              interfaces=["RS232"], price_uah_no_vat=20334.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_quartz_1", model_name="Quartz (1 шлейф)",
              panel_type=PanelType.COMPACT, max_loops=1, devices_per_loop=99, max_total_devices=99,
              interfaces=["RS232", "RS485"], price_uah_no_vat=26832.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_quartz_2", model_name="Quartz (2 шлейфи)",
              panel_type=PanelType.COMPACT, max_loops=2, devices_per_loop=99, max_total_devices=198,
              interfaces=["RS232", "RS485"], price_uah_no_vat=28285.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_compact_lyon_1", model_name="Compact Lyon (1 шлейф)",
              panel_type=PanelType.HYBRID, max_loops=1, devices_per_loop=99, max_total_devices=99,
              interfaces=["RS232", "RS485", "Ethernet"], price_uah_no_vat=24729.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_compact_lyon_2", model_name="Compact Lyon (2 шлейфи)",
              panel_type=PanelType.HYBRID, max_loops=2, devices_per_loop=99, max_total_devices=198,
              interfaces=["RS232", "RS485", "Ethernet"], price_uah_no_vat=25866.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_zafir_1", model_name="Zafir (1 шлейф)",
              panel_type=PanelType.HYBRID, max_loops=1, devices_per_loop=226, max_total_devices=226,
              interfaces=["RS232", "RS485", "Ethernet"], price_uah_no_vat=31492.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_zafir_2", model_name="Zafir (2 шлейфи)",
              panel_type=PanelType.HYBRID, max_loops=2, devices_per_loop=226, max_total_devices=452,
              interfaces=["RS232", "RS485", "Ethernet"], price_uah_no_vat=33145.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_onyx_1", model_name="Onyx (1 шлейф)",
              panel_type=PanelType.MODULAR, max_loops=1, devices_per_loop=226, max_total_devices=226,
              interfaces=["RS232", "RS485", "Ethernet"], price_uah_no_vat=33540.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_onyx_2", model_name="Onyx (2 шлейфи)",
              panel_type=PanelType.MODULAR, max_loops=2, devices_per_loop=226, max_total_devices=452,
              interfaces=["RS232", "RS485", "Ethernet"], price_uah_no_vat=35552.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_lyon_1", model_name="Lyon Remote (1 шлейф)",
              panel_type=PanelType.MODULAR, max_loops=1, devices_per_loop=226, max_total_devices=226,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=62704.0, pricing_status=PricingStatus.QUOTED, pricing_notes="Флагман, алгоритмічна детекція"),
        Panel(panel_id="cofem_lyon_2", model_name="Lyon Remote (2 шлейфи)",
              panel_type=PanelType.MODULAR, max_loops=2, devices_per_loop=226, max_total_devices=452,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=64466.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_lyon_3", model_name="Lyon Remote (3 шлейфи)",
              panel_type=PanelType.MODULAR, max_loops=3, devices_per_loop=226, max_total_devices=678,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=70720.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_lyon_4", model_name="Lyon Remote (4 шлейфи)",
              panel_type=PanelType.MODULAR, max_loops=4, devices_per_loop=226, max_total_devices=904,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=74415.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="cofem_lyon_5", model_name="Lyon Remote (5 шлейфів)",
              panel_type=PanelType.MODULAR, max_loops=5, devices_per_loop=226, max_total_devices=1130,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=78333.0, pricing_status=PricingStatus.ESTIMATED,
              pricing_notes="Ціна оцінена екстраполяцією; уточнити в дистриб'ютора"),
        Panel(panel_id="cofem_lyon_6", model_name="Lyon Remote (6 шлейфів)",
              panel_type=PanelType.MODULAR, max_loops=6, devices_per_loop=226, max_total_devices=1356,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=82250.0, pricing_status=PricingStatus.ESTIMATED,
              pricing_notes="Ціна оцінена екстраполяцією; уточнити в дистриб'ютора"),
        Panel(panel_id="cofem_lyon_7", model_name="Lyon Remote (7 шлейфів)",
              panel_type=PanelType.MODULAR, max_loops=7, devices_per_loop=226, max_total_devices=1582,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=86167.0, pricing_status=PricingStatus.ESTIMATED,
              pricing_notes="Ціна оцінена екстраполяцією; уточнити в дистриб'ютора"),
        Panel(panel_id="cofem_lyon_8", model_name="Lyon Remote (8 шлейфів)",
              panel_type=PanelType.MODULAR, max_loops=8, devices_per_loop=226, max_total_devices=1808,
              network_max_panels=32, interfaces=["RS232", "RS485", "Ethernet"],
              price_uah_no_vat=90083.0, pricing_status=PricingStatus.ESTIMATED,
              pricing_notes="Ціна оцінена екстраполяцією; уточнити в дистриб'ютора"),
    ],
    detectors=[
        Detector(detector_id="cofem_a50s", model_name="A50S", detector_type=DetectorType.SMOKE_OPTICAL,
                 loop_powered=True, algorithmic_features=["drift_compensation", "adaptive_thresholds"],
                 compatible_panel_ids=_ALL_COFEM_PANELS, price_uah_no_vat=1816.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="cofem_a50si", model_name="A50SI", detector_type=DetectorType.SMOKE_OPTICAL,
                 loop_powered=True,
                 algorithmic_features=["drift_compensation", "adaptive_thresholds", "short_circuit_isolator"],
                 compatible_panel_ids=_ALL_COFEM_PANELS, price_uah_no_vat=2013.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="cofem_a50h", model_name="A50H", detector_type=DetectorType.HEAT_MAX,
                 loop_powered=True, compatible_panel_ids=_ALL_COFEM_PANELS,
                 price_uah_no_vat=1727.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="cofem_a50hi", model_name="A50HI", detector_type=DetectorType.HEAT_MAX,
                 loop_powered=True, algorithmic_features=["short_circuit_isolator"],
                 compatible_panel_ids=_ALL_COFEM_PANELS,
                 price_uah_no_vat=1917.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="cofem_a50shi", model_name="A50SHI", detector_type=DetectorType.MULTI_SENSOR,
                 loop_powered=True,
                 algorithmic_features=["drift_compensation", "sensor_fusion", "short_circuit_isolator"],
                 compatible_panel_ids=_ALL_COFEM_PANELS,
                 price_uah_no_vat=1989.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="cofem_a50shild", model_name="A50SHILD", detector_type=DetectorType.MULTI_SENSOR,
                 loop_powered=True,
                 algorithmic_features=["drift_compensation", "sensor_fusion",
                                       "integrated_sounder", "integrated_strobe"],
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=3863.0, pricing_status=PricingStatus.QUOTED),
    ],
    io_modules=[
        IOModule(module_id="cofem_mstay8", model_name="MSTAY8", module_type=IOModuleType.INPUT,
                 inputs_count=8, outputs_count=0, address_consumption=1,
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=5159.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="cofem_mstay", model_name="MSTAY", module_type=IOModuleType.INPUT,
                 inputs_count=2, outputs_count=0, address_consumption=1,
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=2492.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="cofem_mda2ylt", model_name="MDA2YLT", module_type=IOModuleType.OUTPUT,
                 inputs_count=0, outputs_count=2, output_type="voltage_free", output_supervised=True,
                 address_consumption=1, needs_external_power=False,
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=5466.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="cofem_mda1y", model_name="MDA1Y", module_type=IOModuleType.OUTPUT,
                 inputs_count=0, outputs_count=1, output_type="relay", output_supervised=True,
                 address_consumption=1, needs_external_power=True, external_voltage_v=30.0,
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=3322.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="cofem_mda2y", model_name="MDA2Y", module_type=IOModuleType.OUTPUT,
                 inputs_count=0, outputs_count=2, output_type="relay",
                 address_consumption=1, needs_external_power=True, external_voltage_v=30.0,
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=3738.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="cofem_myoa", model_name="MYOA", module_type=IOModuleType.COMBINED,
                 inputs_count=1, outputs_count=1, output_type="relay",
                 address_consumption=1, compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=4568.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="cofem_kmay", model_name="KMAY", module_type=IOModuleType.CONV_ZONE,
                 inputs_count=1, outputs_count=0, address_consumption=1,
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=2906.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="cofem_kaby", model_name="KABY", module_type=IOModuleType.ISOLATOR,
                 inputs_count=0, outputs_count=0, address_consumption=1,
                 compatible_panel_ids=_PANELS_WITH_IO,
                 price_uah_no_vat=2492.0, pricing_status=PricingStatus.QUOTED),
    ],
    sounders=[
        Sounder(sounder_id="cofem_sirend", model_name="SIREND",
                has_sound=True, has_strobe=False, address_consumption=1, loop_powered=True,
                price_uah_no_vat=3805.0, pricing_status=PricingStatus.QUOTED),
        Sounder(sounder_id="cofem_sirendl", model_name="SIRENDL",
                has_sound=True, has_strobe=True, en54_23_category="W-2.4-6",
                address_consumption=1, loop_powered=True,
                price_uah_no_vat=4685.0, pricing_status=PricingStatus.QUOTED),
    ],
    manual_call_points=[
        ManualCallPoint(mcp_id="cofem_pucay", model_name="PUCAY",
                        has_integrated_isolator=True, address_consumption=1,
                        price_uah_no_vat=1418.0, pricing_status=PricingStatus.QUOTED),
    ],
    power_supplies=[],
)
