"""
Каталог Омега — оновлено з реальних прайсів (11.05.2026)
Джерело: FireCompare_Catalog_Forms.xlsx
ВАЖЛИВО: Омега використовує оповіщувачі і MCP виробництва Tiras 
(вказано в самому файлі дистриб'ютора)
"""
from datetime import date

from schemas.catalog import (
    BMSIntegration, Certifications, CertificationStatus, CloudMonitoring,
    DataStatus, Detector, DetectorType, FalseAlarmLevel, FeatureSupport,
    Features, IOModule, IOModuleType, JurisdictionCert, ManualCallPoint,
    Manufacturer, MobileApp, Panel, PanelType, PricingStatus, Redundancy,
    Sounder, SystemType, Tier, UADistributor,
)


OMEGA = Manufacturer(
    manufacturer_id="omega",
    name_ua="Омега",
    name_en="Omega (Project AO)",
    country_iso2="UA",
    tier=Tier.MID,
    system_type=SystemType.ADDRESSABLE_THRESHOLD,
    warranty_months=36,
    ua_distributor=UADistributor(
        company_name="Прямі продажі від виробника (Харків)",
        service_cities=["Київ", "Харків", "Дніпро", "Львів", "Одеса"],
        response_time_hours=24,
    ),
    data_status=DataStatus.COMPLETE,
    last_updated=date(2026, 5, 11),
    notes_internal="Ціни з FireCompare_Catalog_Forms.xlsx. Оповіщувачі і MCP — постачаються від Tiras.",
    notes_strengths=[
        "Резервована шина RS-485 ×2 — унікальна перевага в UA сегменті",
        "Найдешевші адресні сповіщувачі на ринку (СПДОТА 445 грн)",
        "Повна UA-сертифікація і експертиза",
        "Розширена сервісна мережа",
        "Підтримка пожежогасіння (ППУ-ПТ)",
    ],
    notes_weaknesses=[
        "4-адресні блоки БСА/БКА — створюють архітектурний податок",
        "Адресно-порогова архітектура — обмежений захист від хибних",
        "Хмарний моніторинг не передбачено",
        "Обмежена міжнародна сертифікація",
        "Оповіщувачі — постачання через Tiras (залежність)",
    ],
    certifications=Certifications(
        EU_EN54=JurisdictionCert(status=CertificationStatus.PARTIAL),
        UA_DSTU_EN54=JurisdictionCert(status=CertificationStatus.FULL,
                                       certified_parts=["-2", "-4", "-7", "-17", "-18"]),
        UK_BS_LPCB=JurisdictionCert(status=CertificationStatus.NONE),
        US_UL_FM=JurisdictionCert(status=CertificationStatus.NONE),
        iso_9001="ISO 9001:2015",
    ),
    features=Features(
        false_alarm_level=FalseAlarmLevel.BASIC,
        false_alarm_technologies=[],
        cloud_monitoring=CloudMonitoring(available=False),
        mobile_app=MobileApp(available=False),
        bms_integration=BMSIntegration(modbus_rtu=FeatureSupport.GATEWAY),
        voice_alarm=FeatureSupport.NONE,
        wireless_extension=False,
        redundancy=Redundancy(network=True, notes="Резервована шина RS-485 ×2"),
    ),
    panels=[
        Panel(panel_id="omega_pu_p_4", model_name="ПУ-П 4 (4 кільця)",
              panel_type=PanelType.MODULAR, max_loops=4, devices_per_loop=60, max_total_devices=240,
              network_max_panels=8, interfaces=["RS485"],
              price_uah_no_vat=50655.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="omega_pu_p_8", model_name="ПУ-П 8 (8 кілець)",
              panel_type=PanelType.MODULAR, max_loops=8, devices_per_loop=60, max_total_devices=480,
              network_max_panels=8, interfaces=["RS485"],
              price_uah_no_vat=55627.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="omega_ppu_pt_4", model_name="ППУ-ПТ 4 (4 кільця)",
              panel_type=PanelType.MODULAR, max_loops=4, devices_per_loop=60, max_total_devices=240,
              network_max_panels=8, interfaces=["RS485"],
              price_uah_no_vat=59807.0, pricing_status=PricingStatus.QUOTED,
              pricing_notes="З функцією пожежогасіння"),
        Panel(panel_id="omega_ppu_pt_8", model_name="ППУ-ПТ 8 (8 кілець)",
              panel_type=PanelType.MODULAR, max_loops=8, devices_per_loop=60, max_total_devices=480,
              network_max_panels=8, interfaces=["RS485"],
              price_uah_no_vat=65857.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="omega_ppkp_p_4", model_name="ППКП-П 4 (розширення)",
              panel_type=PanelType.MODULAR, max_loops=4, devices_per_loop=60, max_total_devices=240,
              interfaces=["RS485"],
              price_uah_no_vat=44506.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="omega_ppkp_p_8", model_name="ППКП-П 8 (розширення)",
              panel_type=PanelType.MODULAR, max_loops=8, devices_per_loop=60, max_total_devices=480,
              interfaces=["RS485"],
              price_uah_no_vat=47333.0, pricing_status=PricingStatus.QUOTED),
    ],
    detectors=[
        Detector(detector_id="omega_spdota", model_name="СПДОТА",
                 detector_type=DetectorType.SMOKE_OPTICAL, loop_powered=True,
                 compatible_panel_ids=["omega_pu_p_4", "omega_pu_p_8",
                                       "omega_ppu_pt_4", "omega_ppu_pt_8",
                                       "omega_ppkp_p_4", "omega_ppkp_p_8"],
                 price_uah_no_vat=445.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="omega_sptta", model_name="СПТТА",
                 detector_type=DetectorType.HEAT_MAX, loop_powered=True,
                 compatible_panel_ids=["omega_pu_p_4", "omega_pu_p_8",
                                       "omega_ppu_pt_4", "omega_ppu_pt_8",
                                       "omega_ppkp_p_4", "omega_ppkp_p_8"],
                 price_uah_no_vat=360.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="omega_sppta", model_name="СППТА (полум'я)",
                 detector_type=DetectorType.FLAME, loop_powered=True,
                 compatible_panel_ids=["omega_pu_p_4", "omega_pu_p_8"],
                 price_uah_no_vat=4670.0, pricing_status=PricingStatus.QUOTED),
    ],
    io_modules=[
        IOModule(module_id="omega_bsa", model_name="БСА",
                 module_type=IOModuleType.INPUT, inputs_count=4, outputs_count=0,
                 address_consumption=4,
                 compatible_panel_ids=["omega_pu_p_4", "omega_pu_p_8",
                                       "omega_ppu_pt_4", "omega_ppu_pt_8"],
                 price_uah_no_vat=560.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="omega_bka_220", model_name="БКА-220",
                 module_type=IOModuleType.COMBINED, inputs_count=2, outputs_count=1,
                 output_type="relay", address_consumption=4,
                 compatible_panel_ids=["omega_pu_p_4", "omega_pu_p_8",
                                       "omega_ppu_pt_4", "omega_ppu_pt_8"],
                 price_uah_no_vat=925.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="omega_brvu_4", model_name="БРВУ-4",
                 module_type=IOModuleType.OUTPUT, inputs_count=0, outputs_count=4,
                 output_type="relay", address_consumption=4, needs_external_power=True,
                 compatible_panel_ids=["omega_pu_p_4", "omega_pu_p_8",
                                       "omega_ppu_pt_4", "omega_ppu_pt_8"],
                 price_uah_no_vat=10076.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="omega_brvu_8", model_name="БРВУ-8",
                 module_type=IOModuleType.OUTPUT, inputs_count=0, outputs_count=8,
                 output_type="relay", address_consumption=4, needs_external_power=True,
                 compatible_panel_ids=["omega_pu_p_4", "omega_pu_p_8",
                                       "omega_ppu_pt_4", "omega_ppu_pt_8"],
                 price_uah_no_vat=13200.0, pricing_status=PricingStatus.QUOTED),
    ],
    # Sounders — використовуються Tiras
    sounders=[
        Sounder(sounder_id="omega_alarmo_via_tiras", model_name="ALARMO 100 (через Tiras)",
                has_sound=True, has_strobe=False, address_consumption=1, loop_powered=True,
                price_uah_no_vat=1330.0, pricing_status=PricingStatus.QUOTED,
                # Постачається від Tiras, узгоджено в інтеграції
                ),
    ],
    # MCP — теж через Tiras
    manual_call_points=[
        ManualCallPoint(mcp_id="omega_spra", model_name="СПРА",
                        has_integrated_isolator=False, address_consumption=1,
                        price_uah_no_vat=535.0, pricing_status=PricingStatus.QUOTED),
    ],
    power_supplies=[],
)
