"""
Каталог Tiras — оновлено з реальних прайсів (11.05.2026)
Джерело: FireCompare_Catalog_Forms.xlsx
"""
from datetime import date

from schemas.catalog import (
    BMSIntegration, Certifications, CertificationStatus, CloudMonitoring,
    DataStatus, Detector, DetectorType, FalseAlarmLevel, FeatureSupport,
    Features, IOModule, IOModuleType, JurisdictionCert, ManualCallPoint,
    Manufacturer, MobileApp, Panel, PanelType, PricingStatus, Redundancy,
    Sounder, SystemType, Tier, UADistributor,
)


TIRAS = Manufacturer(
    manufacturer_id="tiras",
    name_ua="Tiras",
    name_en="Tiras",
    country_iso2="UA",
    tier=Tier.BUDGET,
    system_type=SystemType.MIXED,
    warranty_months=36,
    ua_distributor=UADistributor(
        company_name="Прямі продажі від виробника",
        service_cities=["Київ", "Львів", "Дніпро", "Одеса", "Харків", "Запоріжжя"],
        response_time_hours=24,
    ),
    data_status=DataStatus.COMPLETE,
    last_updated=date(2026, 5, 11),
    notes_internal="Ціни з FireCompare_Catalog_Forms.xlsx",
    notes_strengths=[
        "Українське виробництво — швидка логістика і сервіс",
        "Найкращий CAPEX серед адресних систем у UA",
        "DETECTO PLUS — передача рівня забруднення на ППКП",
        "Підтримка LiFePO4 батарей",
        "Широка сервісна мережа в Україні",
    ],
    notes_weaknesses=[
        "Обмежена міжнародна сертифікація (тільки ДСТУ EN 54)",
        "Базовий рівень захисту від хибних спрацювань",
        "Хмарний моніторинг через 3rd-party шлюзи",
    ],
    certifications=Certifications(
        EU_EN54=JurisdictionCert(status=CertificationStatus.NONE),
        UA_DSTU_EN54=JurisdictionCert(status=CertificationStatus.FULL,
                                       certified_parts=["-2", "-4", "-7", "-17", "-18"]),
        UK_BS_LPCB=JurisdictionCert(status=CertificationStatus.NONE),
        US_UL_FM=JurisdictionCert(status=CertificationStatus.NONE),
        iso_9001="ISO 9001:2015",
    ),
    features=Features(
        false_alarm_level=FalseAlarmLevel.BASIC,
        false_alarm_technologies=["DETECTO_PLUS_diagnostics"],
        cloud_monitoring=CloudMonitoring(available=False),
        mobile_app=MobileApp(available=False),
        bms_integration=BMSIntegration(modbus_rtu=FeatureSupport.GATEWAY),
        voice_alarm=FeatureSupport.NONE,
        wireless_extension=False,
        redundancy=Redundancy(),
    ),
    
    # Maintenance: український виробник, локальний склад, швидка реакція
    maintenance_time_modifier=1.0,  # стандарт
    avg_part_replacement_cost_uah=500.0,  # детектор Tiras ~500 грн
    service_response_modifier=0.9,  # завжди в наявності, швидка реакція
    
    panels=[
        Panel(panel_id="tiras_prime_a", model_name="PRIME A (2 петлі)",
              panel_type=PanelType.MODULAR, max_loops=2, devices_per_loop=250, max_total_devices=500,
              is_addressable=True,
              relay_limit_scope="shared",
              network_max_panels=8, interfaces=["RS485", "Ethernet"],
              price_uah_no_vat=33170.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="tiras_prime_xl", model_name="PRIME XL (16 зон)",
              panel_type=PanelType.COMPACT, max_loops=16, devices_per_loop=32, max_total_devices=512,
              is_addressable=False,
              relay_limit_scope="shared",
              interfaces=["RS485"],
              price_uah_no_vat=22690.0, pricing_status=PricingStatus.QUOTED,
              pricing_notes="Безадресна, конвенційна"),
        Panel(panel_id="tiras_prime_l", model_name="PRIME L (16 зон)",
              panel_type=PanelType.COMPACT, max_loops=16, devices_per_loop=32, max_total_devices=512,
              is_addressable=False,
              relay_limit_scope="shared",
              interfaces=["RS485"],
              price_uah_no_vat=17100.0, pricing_status=PricingStatus.QUOTED,
              pricing_notes="Безадресна"),
        Panel(panel_id="tiras_prime_m", model_name="PRIME M (8 зон)",
              panel_type=PanelType.COMPACT, max_loops=8, devices_per_loop=32, max_total_devices=256,
              is_addressable=False,
              relay_limit_scope="shared",
              interfaces=["RS485"],
              price_uah_no_vat=9330.0, pricing_status=PricingStatus.QUOTED),
        Panel(panel_id="tiras_prime_s", model_name="PRIME S (4 зони)",
              panel_type=PanelType.COMPACT, max_loops=4, devices_per_loop=32, max_total_devices=128,
              is_addressable=False,
              relay_limit_scope="shared",
              interfaces=["RS485"],
              price_uah_no_vat=8400.0, pricing_status=PricingStatus.QUOTED),
    ],
    detectors=[
        Detector(detector_id="tiras_mlt110", model_name="DETECTO MLT110",
                 detector_type=DetectorType.MULTI_SENSOR, loop_powered=True,
                 algorithmic_features=["short_circuit_isolator"],
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=1378.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="tiras_smk110", model_name="DETECTO SMK110",
                 detector_type=DetectorType.SMOKE_OPTICAL, loop_powered=True,
                 algorithmic_features=["short_circuit_isolator", "dirt_compensation"],
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=1250.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="tiras_smk100", model_name="DETECTO SMK100",
                 detector_type=DetectorType.SMOKE_OPTICAL, loop_powered=True,
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=1020.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="tiras_ht110", model_name="DETECTO HT110",
                 detector_type=DetectorType.HEAT_MAX, loop_powered=True,
                 algorithmic_features=["short_circuit_isolator"],
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=1070.0, pricing_status=PricingStatus.QUOTED),
        Detector(detector_id="tiras_ht100", model_name="DETECTO HT100",
                 detector_type=DetectorType.HEAT_MAX, loop_powered=True,
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=820.0, pricing_status=PricingStatus.QUOTED),
    ],
    io_modules=[
        IOModule(module_id="tiras_am_in4", model_name="AM-IN4",
                 module_type=IOModuleType.INPUT, inputs_count=4, outputs_count=0,
                 address_consumption=1, compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=3890.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="tiras_am_out2r", model_name="AM-OUT2R",
                 module_type=IOModuleType.OUTPUT, inputs_count=0, outputs_count=2,
                 output_type="relay", address_consumption=1,
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=1900.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="tiras_am_out1r_plus", model_name="AM-OUT1R+",
                 module_type=IOModuleType.OUTPUT, inputs_count=0, outputs_count=1,
                 output_type="relay", output_supervised=True, address_consumption=1,
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=1790.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="tiras_am_multi", model_name="AM-Multi",
                 module_type=IOModuleType.COMBINED, inputs_count=2, outputs_count=2,
                 output_type="relay", address_consumption=2,
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=1680.0, pricing_status=PricingStatus.QUOTED),
        IOModule(module_id="tiras_am_multi_plus", model_name="AM-Multi+",
                 module_type=IOModuleType.COMBINED, inputs_count=2, outputs_count=2,
                 output_type="relay", address_consumption=2,
                 compatible_panel_ids=["tiras_prime_a"],
                 price_uah_no_vat=6640.0, pricing_status=PricingStatus.QUOTED,
                 # Дорожчий — з вбудованим АБП
                 ),
    ],
    sounders=[
        Sounder(sounder_id="tiras_alarmo_110", model_name="ALARMO 110",
                has_sound=True, has_strobe=False, address_consumption=1, loop_powered=True,
                price_uah_no_vat=1440.0, pricing_status=PricingStatus.QUOTED),
        Sounder(sounder_id="tiras_alarmo_100", model_name="ALARMO 100",
                has_sound=True, has_strobe=False, address_consumption=1, loop_powered=True,
                price_uah_no_vat=1330.0, pricing_status=PricingStatus.QUOTED),
        Sounder(sounder_id="tiras_osz", model_name="ОСЗ",
                has_sound=True, has_strobe=True, address_consumption=1, loop_powered=False,
                price_uah_no_vat=1040.0, pricing_status=PricingStatus.QUOTED,
                # Конвенційний, але широко використовується
                ),
    ],
    manual_call_points=[
        ManualCallPoint(mcp_id="tiras_mnl110", model_name="DETECTO MNL110",
                        has_integrated_isolator=True, address_consumption=1,
                        price_uah_no_vat=1460.0, pricing_status=PricingStatus.QUOTED),
        ManualCallPoint(mcp_id="tiras_mnl100", model_name="DETECTO MNL100",
                        has_integrated_isolator=False, address_consumption=1,
                        price_uah_no_vat=1300.0, pricing_status=PricingStatus.QUOTED),
    ],
    power_supplies=[],
)
